# Generated by Django 4.0 on 2022-12-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=200)),
                ('token', models.CharField(max_length=300)),
                ('id_apple', models.CharField(max_length=300)),
                ('fb_token', models.CharField(max_length=200)),
                ('is_active', models.IntegerField(default=0)),
                ('balance', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
